monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: notice
      handler: nested
      channels: ["!event"]

    nested:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: notice

    critical:
      type: stream
      path: "%kernel.logs_dir%/critical.log"
      level: critical
      channels: ["!event"]
